services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - red_app

  mysql_server:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_app


  phpmyadmin_app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_server
      PMA_PASSWORD: rootpass
    networks:
      - red_app

  alpine_app:
    image: alpine:latest
    container_name: alpine_app
    volumes:
      - ./src:/app                # código PHP
      - mysql_data:/var/lib/mysql # datos de MySQL
    working_dir: /app
    command: sh -c "while true; do sleep 3600; done"
    networks:
      - red_app

# No es estrictamente necesario declarar volumen y red, Docker Compose los crea automáticamente
volumes:
  mysql_data: {}

networks:
  red_app: {}
